export const ACTION_TYPE = {
  SUCCESS: "SUCCESS",
  SEARCH: "SEARCH",
  MOVIEADDED: "MOVIEADDED",
  ADDTOWATCHLIST: "ADDTOWATCHLIST",
  REMOVEWATCHLIST: "REMOVEWATCHLIST",
  GENRE: "GENRE",
  YEAR: "YEAR",
  RATING: "RATING",
  CLEARFILTER: "CLEARFILTER",
  ADDSTARRED: "ADDSTARRED",
  REMOVESTARRED: "REMOVESTARRED"
};
